# Draft ROS 2 Humble image for elfin_humble_ws.
# Not yet the production Dockerfile (src/Dockerfile is still Noetic).
# Interactive Gazebo / RViz2 / MuJoCo MUST be run with --gpus all.
FROM osrf/ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-moveit \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-controller-manager \
    ros-humble-xacro \
    ros-humble-rviz2 \
    ros-humble-ros-gz \
    ros-humble-gz-ros2-control \
    ros-humble-mujoco-ros2-control \
    python3-colcon-common-extensions \
    python3-rosdep \
    mesa-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /colcon_ws
COPY src ./src
# COLCON_IGNORE on ROS 1 packages is expected until they are ported.

SHELL ["/bin/bash", "-c"]
RUN source /opt/ros/humble/setup.bash \
    && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release \
    && echo "source /colcon_ws/install/setup.bash" >> /root/.bashrc

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
